export const CREATE_FOLDER = "CREATE_FOLDER";
export const EDIT_FOLDER = "EDIT_FOLDER";
export const DELETE_FOLDER = "DELETE_FOLDER";

export const CREATE_NOTE = "CREATE_NOTE";
export const EDIT_NOTE = "EDIT_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";

export const CREATE_NOTESITEM = "CREATE_NOTESITEM";

export const ADD_COMMENT = "ADD_COMMENT";
export const FETCH_COMMENTS_BY_ID = "FETCH_COMMENTS_BY_ID";
